import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Editors from '../components/Editors'

const Home: NextPage = () => {
  return (
    <div className="px-8">
      <Head>
        <title>Online Next Compiler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen px-1 flex flex-col justify-center items-center">
        <h1 className="m-0 leading-3 text-4xl flex items-center gap-2">
          Welcome to
          <span className='flex items-center'>
            <Image className="mr-2" alt='next compiler logo' src="/next-js-icon-logo.png" height={40} width={40}/>EXT Compiler
          </span>
        </h1>
        <br/>
        <Editors/>
      </main>

      <footer className="py-2 flex border-t-2 border-indigo-700 justify-center items-center">
        <a
          className='flex justify-center items-center'
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <span className='mx-2'>&</span>
        <a
          className='flex justify-center items-center'
          href='https://dashboard.render.com/'
          target="_blank"
          rel="noopener noreferrer"
        >
          <span>
            <Image src="https://dashboard.render.com/static/media/logo-redesign-02-word-dark.0811da26fe4b1f9a9b6c642d91bbcf73.svg" alt="Render Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
